# Generated by Django 3.2 on 2021-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('password', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('login_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
