# Generated by Django 3.2 on 2021-06-18 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointInterest',
            fields=[
                ('idpercurso', models.AutoField(db_column='idPercurso', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('latitude_inicio', models.CharField(blank=True, max_length=45, null=True)),
                ('longitude_inicio', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Point_Interest',
            },
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=45, null=True)),
                ('lng', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'road_map',
            },
        ),
        migrations.CreateModel(
            name='ItinearyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_points', models.ForeignKey(db_column='interest_points', on_delete=django.db.models.deletion.DO_NOTHING, to='BestRideApi.pointinterest')),
                ('road_map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BestRideApi.roadmap')),
            ],
            options={
                'db_table': 'itineary_route',
            },
        ),
    ]
