# Generated by Django 3.2 on 2021-06-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestRideApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinearyroute',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pointinterest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roadmap',
            options={'managed': False},
        ),
    ]
