# Generated by Django 3.2 on 2021-05-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestRideApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
