# Generated by Django 3.2.5 on 2021-07-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestRideApi', '0002_auto_20210618_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItinearyRouteInterestPoints',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('itinearyroute_id', models.IntegerField()),
                ('pointinterest_id', models.IntegerField()),
            ],
            options={
                'db_table': 'itineary_route_interest_points',
                'managed': False,
            },
        ),
    ]
