# Generated by Django 3.2 on 2021-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestRideApi', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('iduserinfo', models.IntegerField(db_column='idUserInfo', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('primeiro_nome', models.CharField(blank=True, max_length=45, null=True)),
                ('ultimo_nome', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
