# Generated by Django 3.2.5 on 2021-07-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestRideApi', '0002_auto_20210730_1440'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
