# Generated by Django 3.2 on 2021-05-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestRideApi', '0003_auto_20210514_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuristInfo',
            fields=[
                ('iduserinfo', models.AutoField(db_column='idUserInfo', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('primeiro_nome', models.CharField(blank=True, max_length=45, null=True)),
                ('ultimo_nome', models.CharField(blank=True, max_length=45, null=True)),
                ('data_nasc', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'turist_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
