# Generated by Django 3.2 on 2021-05-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestRideApi', '0004_auto_20210521_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_roles', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_roles',
                'managed': False,
            },
        ),
    ]
