-- MySQL Script generated by MySQL Workbench
-- Sat May 15 15:30:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BestRide
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BestRide
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BestRide` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema bestride
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bestride
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bestride` DEFAULT CHARACTER SET latin1 ;
USE `BestRide` ;

-- -----------------------------------------------------
-- Table `BestRide`.`Condutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`Condutor` (
  `idCondutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `rnat_license` TINYINT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(15) NULL,
  PRIMARY KEY (`idCondutor`),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BestRide`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `modo_pagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BestRide`.`Percurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`Percurso` (
  `idPercurso` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `latitude_inicio` VARCHAR(45) NULL,
  `longitude_inicio` VARCHAR(45) NULL,
  PRIMARY KEY (`idPercurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BestRide`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NULL,
  `login_type` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BestRide`.`Viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`Viagem` (
  `idViagem` INT NOT NULL AUTO_INCREMENT,
  `Condutor_idCondutor` INT NOT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  `Percurso_idPercurso` INT NOT NULL,
  `dataViagem` DATE NULL,
  `User_idUser` INT NOT NULL,
  `horaInicio` DATE NULL,
  `horaFim` DATE NULL,
  PRIMARY KEY (`idViagem`, `Condutor_idCondutor`, `User_idUser`, `Pagamento_idPagamento`, `Percurso_idPercurso`),
  INDEX `fk_Viagem_Condutor1_idx` (`Condutor_idCondutor` ASC),
  INDEX `fk_Viagem_Pagamento1_idx` (`Pagamento_idPagamento` ASC),
  INDEX `fk_Viagem_Percurso1_idx` (`Percurso_idPercurso` ASC),
  INDEX `fk_Viagem_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Viagem_Condutor1`
    FOREIGN KEY (`Condutor_idCondutor`)
    REFERENCES `BestRide`.`Condutor` (`idCondutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `BestRide`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Percurso1`
    FOREIGN KEY (`Percurso_idPercurso`)
    REFERENCES `BestRide`.`Percurso` (`idPercurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `BestRide`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`roteiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`roteiro` (
  `idroteiro` INT NOT NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `Viagem_idViagem` INT NOT NULL,
  PRIMARY KEY (`idroteiro`, `Viagem_idViagem`),
  INDEX `fk_roteiro_Viagem1_idx` (`Viagem_idViagem` ASC),
  CONSTRAINT `fk_roteiro_Viagem1`
    FOREIGN KEY (`Viagem_idViagem`)
    REFERENCES `BestRide`.`Viagem` (`idViagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BestRide`.`avaliacao_roteiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`avaliacao_roteiro` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(80) NULL,
  `roteiro_idroteiro` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_avaliacao_roteiro_roteiro1_idx` (`roteiro_idroteiro` ASC),
  CONSTRAINT `fk_avaliacao_roteiro_roteiro1`
    FOREIGN KEY (`roteiro_idroteiro`)
    REFERENCES `bestride`.`roteiro` (`idroteiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BestRide`.`Info_Extra_Condutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`Info_Extra_Condutor` (
  `idInfo_Extra_Condutor` INT NOT NULL AUTO_INCREMENT,
  `nif` VARCHAR(45) NULL,
  `carta_conducao` VARCHAR(45) NULL,
  `validade_carta` DATE NULL,
  `telemovel` VARCHAR(45) NULL,
  `Condutor_idCondutor` INT NOT NULL,
  PRIMARY KEY (`idInfo_Extra_Condutor`, `Condutor_idCondutor`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC),
  UNIQUE INDEX `carta_conducao_UNIQUE` (`carta_conducao` ASC),
  INDEX `fk_Info_Extra_Condutor_Condutor1_idx` (`Condutor_idCondutor` ASC),
  CONSTRAINT `fk_Info_Extra_Condutor_Condutor1`
    FOREIGN KEY (`Condutor_idCondutor`)
    REFERENCES `BestRide`.`Condutor` (`idCondutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BestRide`.`AgendaViagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`AgendaViagem` (
  `idAgendaViagem` INT NOT NULL AUTO_INCREMENT,
  `Condutor_idCondutor` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `dataAgenda` DATE NULL,
  PRIMARY KEY (`idAgendaViagem`, `Condutor_idCondutor`),
  INDEX `fk_AgendaViagem_Condutor1_idx` (`Condutor_idCondutor` ASC),
  INDEX `fk_AgendaViagem_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_AgendaViagem_Condutor1`
    FOREIGN KEY (`Condutor_idCondutor`)
    REFERENCES `BestRide`.`Condutor` (`idCondutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AgendaViagem_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `BestRide`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BestRide`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`Empresa` (
  `idEmpresa_Condutor` INT NOT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(45) NULL,
  `morada_empresa` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpresa_Condutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BestRide`.`Empresa_Condutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`Empresa_Condutor` (
  `idEmpresa_Condutor` INT NOT NULL AUTO_INCREMENT,
  `Empresa_idEmpresa_Condutor` INT NOT NULL,
  `Condutor_idCondutor` INT NOT NULL,
  PRIMARY KEY (`idEmpresa_Condutor`, `Empresa_idEmpresa_Condutor`, `Condutor_idCondutor`),
  INDEX `fk_Empresa_Condutor_Empresa1_idx` (`Empresa_idEmpresa_Condutor` ASC),
  INDEX `fk_Empresa_Condutor_Condutor1_idx` (`Condutor_idCondutor` ASC),
  CONSTRAINT `fk_Empresa_Condutor_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa_Condutor`)
    REFERENCES `BestRide`.`Empresa` (`idEmpresa_Condutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empresa_Condutor_Condutor1`
    FOREIGN KEY (`Condutor_idCondutor`)
    REFERENCES `BestRide`.`Condutor` (`idCondutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BestRide`.`recuperar_conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`recuperar_conta` (
  `recupera_conta_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`recupera_conta_id`),
  INDEX `fk_recuperar_conta_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_recuperar_conta_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `BestRide`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bestride` ;

-- -----------------------------------------------------
-- Table `bestride`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`user_info` (
  `idUserInfo` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `primeiro_nome` VARCHAR(45) NULL,
  `ultimo_nome` VARCHAR(45) NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`idUserInfo`),
  INDEX `fk_user_info_User1_idx` (`UserID` ASC),
  CONSTRAINT `fk_user_info_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `BestRide`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`avaliacoesCondutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`avaliacoesCondutor` (
  `idavaliacoesCondutor` INT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  `avaliado` VARCHAR(45) NULL,
  `Condutor_idCondutor` INT NOT NULL,
  PRIMARY KEY (`idavaliacoesCondutor`, `Condutor_idCondutor`),
  INDEX `fk_avaliacoesCondutor_Condutor_idx` (`Condutor_idCondutor` ASC),
  CONSTRAINT `fk_avaliacoesCondutor_Condutor`
    FOREIGN KEY (`Condutor_idCondutor`)
    REFERENCES `BestRide`.`Condutor` (`idCondutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`percurso_roteiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`percurso_roteiro` (
  `roteiro_idroteiro` INT NOT NULL,
  `roteiro_Viagem_idViagem` INT NOT NULL,
  `Percurso_idPercurso` INT NOT NULL,
  INDEX `fk_percurso_roteiro_roteiro1_idx` (`roteiro_idroteiro` ASC, `roteiro_Viagem_idViagem` ASC),
  PRIMARY KEY (`roteiro_idroteiro`),
  INDEX `fk_percurso_roteiro_Percurso1_idx` (`Percurso_idPercurso` ASC),
  CONSTRAINT `fk_percurso_roteiro_roteiro1`
    FOREIGN KEY (`roteiro_idroteiro` , `roteiro_Viagem_idViagem`)
    REFERENCES `bestride`.`roteiro` (`idroteiro` , `Viagem_idViagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_percurso_roteiro_Percurso1`
    FOREIGN KEY (`Percurso_idPercurso`)
    REFERENCES `BestRide`.`Percurso` (`idPercurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
