-- MySQL Script generated by MySQL Workbench
-- Thu May 27 22:45:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bestride
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bestride
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bestride` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema bestride
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bestride
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bestride` DEFAULT CHARACTER SET latin1 ;
USE `bestride` ;

-- -----------------------------------------------------
-- Table `bestride`.`road_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`road_map` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lat` VARCHAR(45) NULL,
  `lng` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`avaliacao_roteiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`avaliacao_roteiro` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(80) NULL,
  `roteiro_idroteiro` INT NOT NULL,
  `road_map_id` INT NOT NULL,
  INDEX `fk_avaliacao_roteiro_road_map1_idx` (`road_map_id` ASC),
  PRIMARY KEY (`idComentario`),
  CONSTRAINT `fk_avaliacao_roteiro_road_map1`
    FOREIGN KEY (`road_map_id`)
    REFERENCES `bestride`.`road_map` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NULL,
  `login_type` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `modo_pagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`Viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`Viagem` (
  `idViagem` INT NOT NULL AUTO_INCREMENT,
  `Pagamento_idPagamento` INT NOT NULL,
  `dataViagem` DATE NULL,
  `turist_id` INT NOT NULL,
  `horaInicio` DATE NULL,
  `horaFim` DATE NULL,
  `road_map_id` INT NOT NULL,
  PRIMARY KEY (`idViagem`),
  INDEX `fk_Viagem_Pagamento1_idx` (`Pagamento_idPagamento` ASC),
  INDEX `fk_Viagem_User1_idx` (`turist_id` ASC),
  INDEX `fk_Viagem_road_map1_idx` (`road_map_id` ASC),
  CONSTRAINT `fk_Viagem_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `bestride`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_User1`
    FOREIGN KEY (`turist_id`)
    REFERENCES `bestride`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_road_map1`
    FOREIGN KEY (`road_map_id`)
    REFERENCES `bestride`.`road_map` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`driver_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`driver_info` (
  `idInfo_Extra_Condutor` INT NOT NULL AUTO_INCREMENT,
  `nif` VARCHAR(45) NULL,
  `carta_conducao` VARCHAR(45) NULL,
  `validade_carta` DATE NULL,
  `telemovel` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idInfo_Extra_Condutor`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC),
  UNIQUE INDEX `carta_conducao_UNIQUE` (`carta_conducao` ASC),
  INDEX `fk_driver_info_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_driver_info_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `bestride`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`AgendaViagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`AgendaViagem` (
  `idAgendaViagem` INT NOT NULL AUTO_INCREMENT,
  `turist_id` INT NOT NULL,
  `dataAgenda` DATE NULL,
  `driver_id` INT NOT NULL,
  PRIMARY KEY (`idAgendaViagem`),
  INDEX `fk_AgendaViagem_User1_idx` (`turist_id` ASC),
  INDEX `fk_AgendaViagem_User2_idx` (`driver_id` ASC),
  CONSTRAINT `fk_AgendaViagem_User1`
    FOREIGN KEY (`turist_id`)
    REFERENCES `bestride`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AgendaViagem_User2`
    FOREIGN KEY (`driver_id`)
    REFERENCES `bestride`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`Ponto_Interesse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`Ponto_Interesse` (
  `idPercurso` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `latitude_inicio` VARCHAR(45) NULL,
  `longitude_inicio` VARCHAR(45) NULL,
  PRIMARY KEY (`idPercurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`Empresa` (
  `idEmpresa_Condutor` INT NOT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(45) NULL,
  `morada_empresa` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpresa_Condutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`Empresa_Condutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`Empresa_Condutor` (
  `idEmpresa_Condutor` INT NOT NULL AUTO_INCREMENT,
  `Empresa_idEmpresa_Condutor` INT NOT NULL,
  PRIMARY KEY (`idEmpresa_Condutor`, `Empresa_idEmpresa_Condutor`),
  INDEX `fk_Empresa_Condutor_Empresa1_idx` (`Empresa_idEmpresa_Condutor` ASC),
  CONSTRAINT `fk_Empresa_Condutor_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa_Condutor`)
    REFERENCES `bestride`.`Empresa` (`idEmpresa_Condutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`recuperar_conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BestRide`.`recuperar_conta` (
  `recupera_conta_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(6) NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`recupera_conta_id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `bestride`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`roles` (
  `id_roles` INT NOT NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id_roles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`user_roles` (
  `roles_id_roles` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  INDEX `fk_user_roles_roles1_idx` (`roles_id_roles` ASC),
  INDEX `fk_user_roles_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_user_roles_roles1`
    FOREIGN KEY (`roles_id_roles`)
    REFERENCES `bestride`.`roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `bestride`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`Pontos_Viagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`Pontos_Viagens` (
  `Ponto_Interesse_idPercurso` INT NOT NULL,
  `Viagem_idViagem` INT NOT NULL,
  INDEX `fk_Pontos_Viagens_Ponto_Interesse1_idx` (`Ponto_Interesse_idPercurso` ASC),
  INDEX `fk_Pontos_Viagens_Viagem1_idx` (`Viagem_idViagem` ASC),
  CONSTRAINT `fk_Pontos_Viagens_Ponto_Interesse1`
    FOREIGN KEY (`Ponto_Interesse_idPercurso`)
    REFERENCES `bestride`.`Ponto_Interesse` (`idPercurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pontos_Viagens_Viagem1`
    FOREIGN KEY (`Viagem_idViagem`)
    REFERENCES `bestride`.`Viagem` (`idViagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`log_viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`log_viagem` (
  `idlog_viagem` INT NOT NULL,
  `tempo` DATETIME NULL,
  `Viagem_idViagem` INT NOT NULL,
  PRIMARY KEY (`idlog_viagem`),
  INDEX `fk_log_viagem_Viagem1_idx` (`Viagem_idViagem` ASC),
  CONSTRAINT `fk_log_viagem_Viagem1`
    FOREIGN KEY (`Viagem_idViagem`)
    REFERENCES `bestride`.`Viagem` (`idViagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`turist_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`turist_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `dob` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`id`, `User_idUser`),
  INDEX `fk_turist_info_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_turist_info_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `bestride`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`itineary_route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`itineary_route` (
  `id` INT NOT NULL,
  `Ponto_Interesse_idPercurso` INT NOT NULL,
  `road_map_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Ponto_Interesse_idPercurso`, `road_map_id`),
  INDEX `fk_itineary_route_Ponto_Interesse1_idx` (`Ponto_Interesse_idPercurso` ASC),
  INDEX `fk_itineary_route_road_map1_idx` (`road_map_id` ASC),
  CONSTRAINT `fk_itineary_route_Ponto_Interesse1`
    FOREIGN KEY (`Ponto_Interesse_idPercurso`)
    REFERENCES `bestride`.`Ponto_Interesse` (`idPercurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itineary_route_road_map1`
    FOREIGN KEY (`road_map_id`)
    REFERENCES `bestride`.`road_map` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bestride`.`driver_coments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestride`.`driver_coments` (
  `id` INT NOT NULL,
  `coment` VARCHAR(45) NULL,
  `pontuation` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_driver_coments_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_driver_coments_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `bestride`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bestride` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;